############# deployment.yaml ##########

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment999
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80


---


############ service.yaml #########


apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service999
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
